export const reviewUiMarkup = `
<div class="app">
<aside class="sidebar">
  <div class="brand"><div class="mark">mv</div><div><div class="brand-name">Miao Vision</div><div class="brand-sub">Review Viewer</div></div></div>
  <div><div class="side-section-label" data-i18n="project">当前产物</div><div class="project"><select id="artifactSelect" aria-label="选择交付物" data-i18n-aria="chooseArtifact"></select><b>区域销售表现报告</b><small>Report · 45 行数据 · 本地文件</small></div></div>
  <div><div class="side-section-label"><span data-i18n="history">版本记录</span><span id="versionCount" style="float:right">0 个版本</span></div><div class="versions" id="versionList"></div></div>
  <div class="aside-foot"><b data-i18n="localReview">● 本地审稿</b><p data-i18n="localNote">版本、Spec 与成品保存在本机。快速修改会生成给 Agent 的请求，Viewer 不直接改动文件。</p></div>
</aside>
<main class="main">
  <div class="top"><div><div class="kicker">Artifact review / report</div><h1>区域销售表现报告</h1><p data-i18n="intro">查看每次修订的变化，或选中一个模块提出下一次修改。</p></div><div class="top-tools"><button class="ghost" id="guideToggle" type="button" aria-controls="quickGuide" aria-expanded="true" data-i18n="guideOpen">使用指南</button><button class="ghost" id="languageToggle" aria-label="Switch language">English</button><span class="pill">✓ 证据已验证</span><button class="ghost" id="openMode" data-i18n="openCurrent">预览当前版本 ↗</button><div class="export-control"><button class="ghost" id="exportToggle" type="button" aria-controls="exportMenu" aria-expanded="false" data-i18n="exportCurrent">导出当前版本 ▾</button><div class="export-menu" id="exportMenu" hidden></div></div></div></div>
  <section class="quick-guide" id="quickGuide" aria-labelledby="guideTitle"><div class="guide-head"><div><span class="guide-eyebrow" data-i18n="guideEyebrow">快速上手</span><h2 id="guideTitle" data-i18n="guideTitle">从查看版本到发起修改</h2></div><button class="guide-close" id="guideClose" type="button" data-i18n-aria="guideClose" aria-label="关闭指南">×</button></div><div class="guide-paths"><div class="guide-path"><span class="guide-number">01</span><div><strong data-i18n="guideCompareTitle">比较版本</strong><p data-i18n="guideCompareBody">左侧选版本，再用 A / B 选择要比较的两版。查看产物预览和下方的变化详情。</p></div></div><div class="guide-path"><span class="guide-number">02</span><div><strong data-i18n="guideEditTitle">修改一个模块</strong><p data-i18n="guideEditBody">打开“局部修改”，选标题、图表或洞察。预览会定位并高亮，选好意图后编辑请求并复制给 Agent。</p></div></div><div class="guide-path"><span class="guide-number">03</span><div><strong data-i18n="guideExportTitle">导出当前版本</strong><p data-i18n="guideExportBody">选中左侧版本后，使用右上角导出菜单下载该版本支持的格式。</p></div></div></div><p class="guide-note" data-i18n="guideNote">复制请求不会直接改文件。Agent 修改 Spec、验证并渲染后，新产物会显示为子版本。</p></section>
  <nav class="tabs" aria-label="主要功能" data-i18n-aria="mainFeatures"><button class="tab active" data-screen="versions" data-i18n="compareTab">版本比较</button><button class="tab" data-screen="edit" data-i18n="editTab">局部修改</button></nav>
  <section class="screen active" id="versions">
    <div class="summary"><div><b id="summaryTitle"></b><p id="summaryDetail"></p></div><div class="signal"><span class="good" id="dataSignal"></span><span class="good" id="evidenceSignal"></span><span id="changeSignal"></span></div></div>
    <div class="compare-toolbar"><div class="pick"><label for="baseVersion" data-i18n="baseline">基准 A</label><select id="baseVersion"></select></div><button class="swap" id="swap" aria-label="交换比较版本" data-i18n-aria="swapVersions" title="交换版本" data-i18n-title="swapVersions">⇄</button><div class="pick"><label for="targetVersion" data-i18n="comparison">对比 B</label><select id="targetVersion"></select></div></div>
    <div class="compare-grid"><article class="version-panel"><div class="panel-head"><div><strong id="leftLabel"></strong><small id="leftMeta"></small></div><span class="letter">A</span></div><div id="leftReport"></div></article><article class="version-panel"><div class="panel-head"><div><strong id="rightLabel"></strong><small id="rightMeta"></small></div><span class="letter">B</span></div><div id="rightReport"></div></article></div>
    <div class="diff-list"><h3 data-i18n="changeDetails">变化详情</h3><div id="diffRows"></div></div><p class="mock-note" data-i18n="previewNote">预览显示已渲染的真实 HTML 产物。</p>
  </section>
  <section class="screen" id="edit"><div class="edit-layout"><div class="edit-preview"><h2 class="section-title" data-i18n="currentModules">当前版本 · 可选中的模块</h2><p class="section-sub" id="selectHint" data-i18n="selectHint">点击报告标题或右侧模块列表，生成限定范围的修改请求。</p><div id="editReport"></div><p class="hint" data-i18n="highlightHint">高亮只用于选中目标，实际修改仍需经过 Spec 验证。</p></div><aside class="edit-panel"><h2 class="section-title" data-i18n="editThis">修改这一块</h2><p class="section-sub" data-i18n="scopeHint">只携带目标模块、原值和必要证据，减少 Agent 读取范围。</p><div class="group"><div class="group-label" data-i18n="targetModule">目标模块</div><div id="targets"></div></div><div class="group"><div class="group-label" data-i18n="editIntent">修改意图</div><div class="chips" id="intents"><button class="chip active" data-intent="conclusion">突出结论</button><button class="chip" data-intent="shorter">更简洁</button><button class="chip" data-intent="custom">自定义要求</button></div></div><div class="group"><div class="group-label" data-i18n="agentRequest">发送给 Agent 的请求，可编辑</div><textarea class="prompt" id="prompt" aria-label="可编辑修改请求" data-i18n-aria="editableRequest"></textarea><div class="edit-footer"><small data-i18n="scopedRevision">限定模块 · 验证后生成子版本</small><button class="primary" id="copyPrompt" data-i18n="copyRequest">复制修改请求</button></div></div></aside></div></section>
</main></div><div class="toast" id="toast" role="status"></div>
`
