import type { ChartCatalogItem } from "./chart-catalog-types"

export const EXTENDED_CATALOG: ChartCatalogItem[] = [
  {
    id: 'progress',
    displayName: 'Progress Bar',
    compactFor: 'kpi,completion,target-vs-actual',
    requires: 'measure',
    transformRecipe: 'agg(measure)>single_value',
    avoid: 'no_max_setting,raw_rows',
    requiredEncodings: ['value'],
    allowedTransforms: ['aggregate', 'filter'],
    bestFor: ['completion rate', 'goal attainment', 'resource utilization'],
    antiPatterns: ['without a max reference (defaults to 100)'],
    rules: []
  },
  {
    id: 'sparkline',
    displayName: 'Sparkline',
    compactFor: 'mini-trend,inline',
    requires: 'ordered+measure',
    transformRecipe: 'sort(x)',
    avoid: 'no_sort,sparse_data',
    requiredEncodings: ['x', 'y'],
    allowedTransforms: ['sort', 'limit', 'filter'],
    bestFor: ['inline trend showing', 'mini time series in tables', 'volume direction'],
    antiPatterns: ['standalone (too small for detail)', 'without sort transform'],
    rules: []
  },
  {
    id: 'delta',
    displayName: 'Delta Indicator',
    compactFor: 'change,comparison',
    requires: 'measure',
    transformRecipe: 'agg(measure)>single_value',
    avoid: 'no_reference,raw_rows',
    requiredEncodings: ['value'],
    allowedTransforms: ['aggregate', 'filter'],
    bestFor: ['period-over-period change', 'vs target comparison', 'trend direction callout'],
    antiPatterns: ['without a clear reference period', 'as the only chart in a report'],
    rules: []
  },
  {
    id: 'funnel',
    displayName: 'Funnel Chart',
    compactFor: 'conversion,dropoff,stages',
    requires: 'dim+measure',
    transformRecipe: 'agg>sort(desc)',
    avoid: 'dim>10,non_sequential',
    requiredEncodings: ['x', 'y'],
    allowedTransforms: ['aggregate', 'sort', 'limit', 'filter'],
    bestFor: ['conversion rate stages', 'sales pipeline', 'step-by-step dropoff'],
    antiPatterns: ['non-hierarchical categories (use bar)', 'too many stages without grouping'],
    rules: []
  },
  {
    id: 'gauge',
    displayName: 'Gauge',
    compactFor: 'kpi,target-vs-actual,threshold',
    requires: 'measure',
    transformRecipe: 'agg(measure)>single_value',
    avoid: 'no_max_setting,raw_rows',
    requiredEncodings: ['value'],
    allowedTransforms: ['aggregate', 'filter'],
    bestFor: ['goal attainment', 'threshold monitoring', 'single KPI with min/max context'],
    antiPatterns: ['without a max reference (defaults to 100)', 'as the only chart in a report'],
    rules: []
  },
  {
    id: 'bubble',
    displayName: 'Bubble Chart',
    compactFor: 'relationship,3-variable',
    requires: 'measure+measure+measure',
    transformRecipe: 'raw_or_limit',
    avoid: 'sparse_data,single_measure',
    requiredEncodings: ['x', 'y', 'size'],
    allowedTransforms: ['sort', 'limit', 'filter'],
    bestFor: ['three-variable correlation', 'size-weighted distribution', 'multi-dimensional comparison'],
    antiPatterns: ['missing size encoding (use scatter)', 'too many bubbles without labels'],
    rules: []
  },
  {
    id: 'boxplot',
    displayName: 'Box Plot',
    compactFor: 'distribution,outliers,quartiles',
    requires: 'measure+(optional dim)',
    transformRecipe: 'compute_stats',
    avoid: 'rows<10,non_numeric',
    requiredEncodings: ['y'],
    allowedTransforms: ['filter'],
    bestFor: ['value distribution per category', 'outlier detection', 'comparing medians across groups'],
    antiPatterns: ['fewer than 10 data points (unreliable)', 'without a dimension (use histogram)'],
    minDataPoints: 10,
    rules: []
  },
  {
    id: 'waterfall',
    displayName: 'Waterfall Chart',
    compactFor: 'financial,breakdown,cumulative',
    requires: 'dim+measure',
    transformRecipe: 'sort(order)>compute_running',
    avoid: 'no_sort,non_numeric',
    requiredEncodings: ['x', 'y'],
    allowedTransforms: ['sort', 'filter'],
    bestFor: ['financial breakdown', 'profit/loss bridges', 'month-over-month changes'],
    antiPatterns: ['without a running total (use bar)', 'unsorted categories'],
    rules: []
  },
  {
    id: 'radar',
    displayName: 'Radar Chart',
    compactFor: 'multi-dimension,profile',
    requires: 'dim+measure(>=3)',
    transformRecipe: 'none',
    avoid: 'dim<3,too_many_series',
    requiredEncodings: ['x', 'y'],
    allowedTransforms: ['sort', 'filter'],
    bestFor: ['performance profiling', 'skill assessment', 'multi-faceted comparison'],
    antiPatterns: ['fewer than 3 axes (use bar)', 'more than 8 axes (too dense)'],
    minDataPoints: 3,
    rules: []
  },
  {
    id: 'calendar',
    displayName: 'Calendar Heatmap',
    compactFor: 'time-pattern,density',
    requires: 'date+measure',
    transformRecipe: 'agg(date)>grid',
    avoid: 'sparse_dates,rows<10',
    requiredEncodings: ['x', 'value'],
    allowedTransforms: ['aggregate', 'filter'],
    bestFor: ['daily activity patterns', 'time-based density', 'year-over-year day comparison'],
    antiPatterns: ['fewer than 10 data points', 'non-temporal x-axis'],
    rules: []
  },
  {
    id: 'treemap',
    displayName: 'Treemap',
    compactFor: 'proportion,hierarchy,nesting',
    requires: 'label+value',
    transformRecipe: 'agg>sort(desc)>limit(30)',
    avoid: 'many_labels_no_limit',
    requiredEncodings: ['label', 'value'],
    allowedTransforms: ['aggregate', 'sort', 'limit', 'filter'],
    bestFor: ['part-to-whole with many categories', 'hierarchical proportions'],
    antiPatterns: ['too many items without limit (cluttered)', 'negative values'],
    rules: []
  },
  {
    id: 'pivot',
    displayName: 'Pivot Table',
    compactFor: 'cross-tab,crosstab,matrix',
    requires: 'row+column+value',
    transformRecipe: 'pre-aggregate_rows',
    avoid: 'too_many_cells',
    requiredEncodings: ['x', 'y', 'value'],
    allowedTransforms: ['filter'],
    bestFor: ['cross-tabulation', 'multi-dimensional summary'],
    antiPatterns: ['raw rows without aggregation', 'too many row/column combinations'],
    rules: []
  },
  {
    id: 'sankey',
    displayName: 'Sankey Diagram',
    compactFor: 'flow,pathway,movement',
    requires: 'source+target+value',
    transformRecipe: 'agg(source,target)>encode(value)',
    avoid: 'too_many_links,no_aggregate',
    requiredEncodings: ['x', 'y', 'value'],
    allowedTransforms: ['aggregate', 'filter'],
    bestFor: ['flow between categories', 'energy/material movement', 'conversion paths'],
    antiPatterns: ['raw links without aggregation', 'more than 30 links (too dense)'],
    rules: []
  },
  {
    id: 'infographic-kpi',
    displayName: 'Infographic KPI Card',
    compactFor: 'kpi,summary,fact',
    requires: 'measure',
    transformRecipe: 'agg(measure)>single_value',
    avoid: 'raw_rows',
    requiredEncodings: ['value'],
    allowedTransforms: ['aggregate', 'filter'],
    bestFor: ['standalone KPI with infographic styling', 'visual fact callout'],
    antiPatterns: ['more than 4 per report', 'without a supporting visual'],
    rules: []
  },
  {
    id: 'infographic-list',
    displayName: 'Infographic List',
    compactFor: 'list,items,ranking',
    requires: 'label+value',
    transformRecipe: 'sort>limit',
    avoid: 'raw_rows_no_sort',
    requiredEncodings: ['x', 'y'],
    allowedTransforms: ['sort', 'limit', 'filter'],
    bestFor: ['ranked item list', 'top-N with visual styling'],
    antiPatterns: ['too many items without limit'],
    rules: []
  },
  {
    id: 'infographic-flow',
    displayName: 'Infographic Flow',
    compactFor: 'process,steps,sequence',
    requires: 'x+value',
    transformRecipe: 'sort(x)',
    avoid: 'no_sort',
    requiredEncodings: ['x', 'y'],
    allowedTransforms: ['sort', 'limit', 'filter'],
    bestFor: ['step-by-step process', 'sequential flow visualization'],
    antiPatterns: ['more than 7 steps (too long)'],
    rules: []
  },
  {
    id: 'infographic-hierarchy',
    displayName: 'Infographic Hierarchy',
    compactFor: 'tree,org,structure',
    requires: 'label+value',
    transformRecipe: 'none',
    avoid: 'deep_nesting',
    requiredEncodings: ['label', 'value'],
    allowedTransforms: ['filter'],
    bestFor: ['organizational structure', 'tree-like classification'],
    antiPatterns: ['deep nesting (more than 3 levels)'],
    rules: []
  },
  {
    id: 'infographic-comparison',
    displayName: 'Infographic Comparison',
    compactFor: 'side-by-side,contrast',
    requires: 'measure',
    transformRecipe: 'none',
    avoid: 'single_row',
    requiredEncodings: ['x', 'y'],
    allowedTransforms: ['sort', 'filter'],
    bestFor: ['side-by-side comparison', 'before/after pairs'],
    antiPatterns: ['fewer than 2 items (use bigvalue)'],
    rules: []
  }
]
