import * as YAML from 'yaml'
import { agentError, isAgentError } from './errors'
import { getCatalogEntries } from './spec-validator'
import { analyzeContextSchema } from './context-schema'
import { CHART_CATALOG } from './chart-catalog'
import { BLOCK_REGISTRY, getBlockById } from './report-block-registry'
import type { BlockMatchContext, ReportBlockResolver } from './report-block-registry'
import type { AgentChartSpec } from './types'
import { stringFlag, requiredFlag, writeOutput, fail, readJson } from './cli-utils'
import type { CliArgs } from './cli-utils'

export function runCatalog(args: CliArgs): unknown {
  if (args.flags['for-llm'] === true) {
    const catalog = {
      charts: CHART_CATALOG.map(c => ({
        id: c.id,
        requiredEncodings: c.requiredEncodings,
        allowedTransforms: c.allowedTransforms,
        rules: c.rules.map(r => r.expression),
        bestFor: c.bestFor,
        antiPatterns: c.antiPatterns
      })),
      version: '1.0.0'
    }
    const outputPath = stringFlag(args, 'output')
    if (outputPath) {
      writeOutput(outputPath, `${JSON.stringify(catalog, null, 2)}\n`)
      return { ok: true, value: { output: outputPath } }
    }
    return { ok: true, value: catalog }
  }
  return { ok: true, value: { charts: getCatalogEntries() } }
}

export function runBlock(args: CliArgs): unknown {
  const subcommand = args.positional[0]
  if (subcommand !== 'instantiate') {
    return fail(agentError('UNKNOWN_SUBCOMMAND', `Unknown block subcommand '${subcommand ?? '(none)'}'. Supported: instantiate`, { subcommand }))
  }

  const blockId = args.positional[1]
  if (!blockId) {
    return fail(agentError('MISSING_INPUT', 'Usage: miao-viz block instantiate <block-id> --context <context.json> [--output <file>]'))
  }

  const contextPath = requiredFlag(args, 'context')
  if (isAgentError(contextPath)) return fail(contextPath)

  const raw = readJson<unknown>(contextPath)
  const unwrapped = (raw as { ok?: unknown; value?: unknown }).ok === true
    ? (raw as { value: unknown }).value
    : raw
  const parsed = analyzeContextSchema.safeParse(unwrapped)
  if (!parsed.success) {
    return fail(agentError('INVALID_CONTEXT', `context.json format is invalid: ${parsed.error.issues.map(i => i.message).join('; ')}`, { contextPath }))
  }
  const ctx = parsed.data

  const resolver = getBlockById(blockId)
  if (!resolver) {
    return fail(agentError('UNKNOWN_BLOCK_ID', `Block id '${blockId}' not found. Available: ${BLOCK_REGISTRY.map(b => b.id).join(', ')}`, { blockId, availableIds: BLOCK_REGISTRY.map(b => b.id) }))
  }

  const matchCtx: BlockMatchContext = {
    fields: ctx.fields,
    evidence: ctx.evidence,
    catalog: ctx.catalog,
    sampleWarnings: ctx.sampleWarnings
  }

  const decision = resolver.canUse(matchCtx)
  if (!decision.ok) {
    return fail(agentError('BLOCK_NOT_APPLICABLE', `Block '${blockId}' cannot be used: ${decision.reason}`, { blockId, reason: decision.reason }))
  }

  const variables = resolver.defaultVariables(matchCtx)
  const compiled = resolver.compile(variables, matchCtx)
  const draft = buildBlockDraft(resolver, variables, decision.score, compiled)

  const outputPath = stringFlag(args, 'output')
  if (outputPath) {
    writeOutput(outputPath, draft)
    return { ok: true, value: { output: outputPath, blockId, score: decision.score } }
  }
  return { ok: true, value: { yaml: draft, blockId, score: decision.score } }
}

function buildBlockDraft(
  resolver: ReportBlockResolver,
  variables: Record<string, unknown>,
  score: number,
  compiled: { charts: AgentChartSpec[]; insights?: string[] }
): string {
  const varSummary = Object.entries(variables).map(([k, v]) => `${k}=${v}`).join(', ')
  const yamlBody = YAML.stringify({ charts: compiled.charts, insights: compiled.insights ?? [] })
  const checks = resolver.qualityChecks.map(c => `# [ ] ${c}`).join('\n')
  return [
    `# Generated by: miao-viz block instantiate ${resolver.id}`,
    `# Block: ${resolver.id} (score: ${score.toFixed(2)})`,
    `# Variables: ${varSummary}`,
    `# IMPORTANT: Review field names, adjust variables, fill insights[] before validate`,
    '',
    yamlBody,
    '# Quality checks (from block definition):',
    checks
  ].join('\n')
}
