import { agentError, isAgentError } from './errors'
import { parseAnalyzeContext } from './context-schema'
import { getTemplateById, TEMPLATE_REGISTRY, templateInfo, templateSpecToYaml } from './report-template-registry'
import type { BlockMatchContext } from './report-block-registry'
import { fail, readJson, requiredFlag, stringFlag, writeOutput } from './cli-utils'
import type { CliArgs } from './cli-utils'

export function runTemplate(args: CliArgs): unknown {
  const subcommand = args.positional[0]
  if (subcommand === 'list') {
    return {
      ok: true,
      value: TEMPLATE_REGISTRY.map(templateInfo)
    }
  }

  if (subcommand === 'inspect') {
    const templateId = args.positional[1]
    if (!templateId) return fail(agentError('MISSING_INPUT', 'Usage: miao-viz spec template inspect <template-id>'))
    const template = getTemplateById(templateId)
    if (!template) return fail(agentError('UNKNOWN_TEMPLATE_ID', `Template id '${templateId}' not found.`, { availableIds: TEMPLATE_REGISTRY.map(t => t.id) }))
    return { ok: true, value: templateInfo(template) }
  }

  if (subcommand === 'instantiate') {
    return runTemplateInstantiate(args)
  }

  return fail(agentError('UNKNOWN_SUBCOMMAND', `Unknown template subcommand '${subcommand ?? '(none)'}'. Supported: list, inspect, instantiate`, { subcommand }))
}

function runTemplateInstantiate(args: CliArgs): unknown {
  const templateId = args.positional[1]
  if (!templateId) {
    return fail(agentError('MISSING_INPUT', 'Usage: miao-viz spec template instantiate <template-id> --context <context.json> [--output <file>]'))
  }

  const contextPath = requiredFlag(args, 'context')
  if (isAgentError(contextPath)) return fail(contextPath)

  const ctx = parseAnalyzeContext(readJson<unknown>(contextPath))
  if (!ctx) return fail(agentError('INVALID_CONTEXT', 'context.json format is invalid.', { contextPath }))

  const template = getTemplateById(templateId)
  if (!template) {
    return fail(agentError('UNKNOWN_TEMPLATE_ID', `Template id '${templateId}' not found.`, { templateId, availableIds: TEMPLATE_REGISTRY.map(t => t.id) }))
  }

  const matchCtx: BlockMatchContext = {
    fields: ctx.fields,
    evidence: ctx.evidence,
    catalog: ctx.catalog,
    sampleWarnings: ctx.sampleWarnings,
    metricCandidates: ctx.metricCandidates
  }
  const decision = template.canUse(matchCtx)
  if (!decision.ok) {
    return fail(agentError('TEMPLATE_NOT_APPLICABLE', `Template '${templateId}' cannot be used: ${decision.reason}`, { templateId, reason: decision.reason }))
  }

  const spec = template.instantiate(matchCtx)
  const yaml = [
    `# Generated by: miao-viz template instantiate ${template.id}`,
    `# Template: ${template.id} (score: ${decision.score.toFixed(2)})`,
    '# IMPORTANT: Review chart order and fill structured insights[] before validate',
    '',
    templateSpecToYaml(spec)
  ].join('\n')

  const outputPath = stringFlag(args, 'output')
  if (outputPath) {
    writeOutput(outputPath, yaml)
    return { ok: true, value: { output: outputPath, templateId, score: decision.score } }
  }
  return { ok: true, value: { yaml, templateId, score: decision.score } }
}
