export const VALIDATOR_ERROR_CODES = {
  UNSUPPORTED_TRANSFORM: 'UNSUPPORTED_TRANSFORM',
  INVALID_TRANSFORM: 'INVALID_TRANSFORM',
  EVIDENCE_PATH_NOT_FOUND: 'EVIDENCE_PATH_NOT_FOUND',
  INSIGHT_EVIDENCE_NOT_FOUND: 'INSIGHT_EVIDENCE_NOT_FOUND'
} as const

export type ValidatorErrorCode = (typeof VALIDATOR_ERROR_CODES)[keyof typeof VALIDATOR_ERROR_CODES]

export const VERIFY_ISSUE_CODES = {
  INSIGHT_FORBIDDEN_WORD_STRICT: 'INSIGHT_FORBIDDEN_WORD_STRICT',
  INSIGHT_MISSING_CAVEAT_STRICT: 'INSIGHT_MISSING_CAVEAT_STRICT',
  INSIGHT_NUMERIC_CLAIM_WITHOUT_EVIDENCE_STRICT: 'INSIGHT_NUMERIC_CLAIM_WITHOUT_EVIDENCE_STRICT',
  INSIGHT_TREND_WITHOUT_TIME_STRICT: 'INSIGHT_TREND_WITHOUT_TIME_STRICT',
  INSIGHT_STRONG_CLAIM_WITHOUT_EVIDENCE_STRICT: 'INSIGHT_STRONG_CLAIM_WITHOUT_EVIDENCE_STRICT',
  INSIGHT_REQUIRED_EVIDENCE_MISSING_STRICT: 'INSIGHT_REQUIRED_EVIDENCE_MISSING_STRICT',
  INSIGHT_TYPE_NOT_ALLOWED_STRICT: 'INSIGHT_TYPE_NOT_ALLOWED_STRICT',
  BLOCK_REQUIRED_EVIDENCE_MISSING_STRICT: 'BLOCK_REQUIRED_EVIDENCE_MISSING_STRICT',
  TEMPLATE_REQUIRED_EVIDENCE_MISSING_STRICT: 'TEMPLATE_REQUIRED_EVIDENCE_MISSING_STRICT'
} as const

export type VerifyIssueCode = (typeof VERIFY_ISSUE_CODES)[keyof typeof VERIFY_ISSUE_CODES]

export const CATALOG_RULE_CODES = {
  X_MUST_BE_DIMENSION: 'X_MUST_BE_DIMENSION',
  BAR_NO_AGGREGATE: 'BAR_NO_AGGREGATE',
  TOO_MANY_CATEGORIES: 'TOO_MANY_CATEGORIES',
  X_MUST_BE_TEMPORAL: 'X_MUST_BE_TEMPORAL',
  MISSING_SORT_TRANSFORM: 'MISSING_SORT_TRANSFORM',
  PIE_NO_AGGREGATE: 'PIE_NO_AGGREGATE',
  TOO_MANY_SLICES: 'TOO_MANY_SLICES',
  BIGVALUE_NO_REDUCTION: 'BIGVALUE_NO_REDUCTION',
  SCATTER_NEEDS_TWO_MEASURES: 'SCATTER_NEEDS_TWO_MEASURES',
  HISTOGRAM_SMALL_SAMPLE: 'HISTOGRAM_SMALL_SAMPLE',
  TABLE_TOO_MANY_COLUMNS: 'TABLE_TOO_MANY_COLUMNS'
} as const

export type CatalogRuleCode = (typeof CATALOG_RULE_CODES)[keyof typeof CATALOG_RULE_CODES]
